baseURL: "/"
title: Muhammad Abdul Hafiz
paginate: 5
theme: PaperMod

enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false

minify:
  disableXML: true
  minifyOutput: true

params:
  env: production # to enable google analytics, opengraph, twitter-cards and schema.
  title: Muhammad Abdul Hafiz
  description: ""
  keywords: []
  author: Muhammad Abdul Hafiz
  images: []
  DateFormat: "January 2, 2006"
  defaultTheme: dark # auto, dark, light
  disableThemeToggle: true

  ShowReadingTime: true
  ShowShareButtons: false
  ShowPostNavLinks: true
  ShowBreadCrumbs: true
  ShowCodeCopyButtons: true
  ShowWordCount: true
  ShowRssButtonInSectionTermList: true
  UseHugoToc: true
  disableSpecial1stPost: false
  disableScrollToTop: false
  comments: false
  hidemeta: false
  hideSummary: false
  showtoc: false
  tocopen: false

  label:
    text: "$ cd ~"

  profileMode:
    enabled: true
    title: Muhammad Abdul Hafiz

  socialIcons:
    - name: email
      url: "mailto:jay@mjah.xyz"
    - name: github
      url: "https://github.com/mjah"
    - name: x
      url: "https://x.com/_mjah"
    - name: linkedin
      url: "https://www.linkedin.com/in/muhammad-abdul-hafiz/"

menu:
  main:
    - identifier: about
      name: About
      url: about/
      weight: 10
